### ISSUE TITLE
White line at top of screen

### ISSUE THREAD

**Issue by konradbnet** [mikepenz/wall-splash-android#11]
When I set wallpaper using your APP, it creates ~1 px light/white line at top of screen.
Nexus 5, android 5.0.1, same problem on default launcher/nova. Tell me if you will need sny more informations. Screenshot: https://copy.com/sdJhjMvPuYcRNviS

**Comment by konradbnet** [comment]
Meh, if it's not visible then: http://konradb.net/wall/

**Comment by mikepenz** [comment]
@konradbnet thanks for the report. 

I'm not sure what causes the issue. I use the default SetWallpaper function provided by android. 
It seems only some devices get this error. It can be "solved" by long-clicking the set wallpaper button.

I'll try to find a work-around for this.

**Comment by mikepenz** [comment]
@konradbnet if i try some solution would you be so kind to test them? I am not able to reproduce this on my phone.

**Comment by konradbnet** [comment]
@mikepenz sure, let me know when you create something.

**Comment by mikepenz** [comment]
@konradbnet is it fixed with the newest version 1.6.6 which is in the play store?

**Comment by konradbnet** [comment]
No, it is not fixed. But I have used the new feature to download wallpaper and it shows that it is probably downloading function problem. The "RAW" wallpaper after hitting 'save' option. https://copy.com/zUmLjEqnBGq3IwZV
You need to open in dark background.

**Comment by mikepenz** [comment]
@konradbnet is it an issue with each wallpaper? or just this one?

**Comment by konradbnet** [comment]
Each one, some have more visible line, other less. https://copy.com/ssED6nxoGShwecUU https://copy.com/1qCxNpGXUyEsHuT3

**Comment by mikepenz** [comment]
@konradbnet really strange. i'll search for the original image url. and look if it also includes the white line

**Comment by mikepenz** [comment]
it seems as it must be an issue of the resize algorithm of imgix: https://unsplash.imgix.net/photo-1417722009592-65fa261f5632?q=75&fm=jpg 

the original image does not seem to have the problem. 

the main issue is i can't download the full size images because some phones won't handle it. 

Not yet sure how to solve this issue.

Have you tried setting the wallpaper with long-clicking the set wallpaper button and opening the crop activity?

**Comment by mikepenz** [comment]
@konradbnet i believe i found a solution. and it should already be included within the newest v1.8.0 i'll publish later today. 

You can test it right now by joining the beta: https://betas.to/LhFee4LX

**Comment by konradbnet** [comment]
The latest version in beta APP is 1.6. :( 
When I long-click button, and set wallpaper with that crop activity, there is still white line and there is no wallpaper under navigation keys (only black bar).

**Comment by mikepenz** [comment]
sorry the link was not up2date -> https://betas.to/ZtoJXpCC

**Comment by konradbnet** [comment]
Yeah, works like a charm.

**Comment by mikepenz** [comment]
Thanks for your help ;).

The update will be live in the play store within the next couple of hours.
